spring:
  application:
    name: "configserver"
  profiles:
  # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"

          # search-locations: "file:///C://Users//glazd//OneDrive//Bureau//CERTIFIED JAVA - SPRING//getting-started-source-code//spring//micro-services//easybank-file-system-location-config"

server:
  port: 8071
